language: python
python:
  - "3.4"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - sed 's/ssl_certificate:/# ssl_certificate:/g;s/ssl_key:/# ssl_key:/g' configuration.yaml > .travis_configuration.yaml
  - mv .travis_configuration.yaml configuration.yaml
  - mv .travis_secrets.yaml secrets.yaml
notifications:
  slack:
    secure: ahTPwnIWKtyzUWYr4RdvuiM0VdK6P/mcMPoOhW/dAtIjI/buHNtVmPS+kz2fDWOC1ibScBye0QlslJ+tBu+jX0p6UZ37rhodTNBGtyaAJyz9fo7jRz5hRXQgFb7qy2XlANDViJqKtnrmYNWRs5DcSqHJsE6GUiYvl3dBK/tAcs98rKC8VeTXrTLs0+TgKeUz1I/vAoO0DmYv4oeIOOtotmE3EnnTxIrIX/HPh+oKtRCxcIt/ZTMJRNiiuKowu4qQtic+ZQ8CYX9K+vmfuoiQBlvtevRXIMf5DjbmYJ26oOpvUM9blCsGdFuJGMpB5YH7HVBzQFVewFmS0In/vcDlkmfFCYNR9TdPCrwAknNFqI6bOrLC0zGzMoeoBVfIDQEB5cmoNUgH90AL4JHpD5NHEzhd+NAJ898+YmAGnlKfSh6K4XPJxwYw4hF1M5ei2hiFLlSt2v3VBhX5ZPxK1IVAu1OwGKnPMe9TZr9UR8BRglI7koodEi7549AJrbiS+7OVftCRmf4W/I/f0ITqDm+J/1a55j5zQ49F56/JOZKhLdXC6onu4HrFiYe25KkoV6IOgQZoWyXvMjQKk/T99QtcBpFC0rxVX2tlcIoIoaR++OsT1bSumZ3xPT1K/4CAPkKRcgKNvZ3eeHnA7HgBpPKvjZNRyCWI1XHff8ArN8w0IzA=
  webhooks:
    secure: "JpxFaDNJJi1Zvbk02UOfstOle091lda6rkgIhJ+f4REeOyfPVxp/Ehl0HGJ1RHjF6vy1ls+WA7b8fOlNDRrPWVdUARg3n55MjuSz8ICD2CyOXfcUq6BXYtFa3RLz1a2Sw/1kRUKGuw1jMnKRIkLzKSmarYwkWh6QmWH7RnbWqyYI5oMBWawlN7cooSKWnXizbOH1NdGETdtZdUICyLmPhpHu2+DNnxJTCxo+4mhEo/I75gyxnPZkU6ck4m/iYyv3zN4sIhA0F6NP74z4riKqiupbKhT14do8i2OI/wWI6E8NV4U+rD5KGZScFOwv3hkkABedt9plnAE0QNhQfG4W1Hfe8lRtiYB0pYJwN6j+Lqz0ijM2RifnQS8UWyq0V4xnl9zGc6SiW/Om9CUQv1nq7LZIB/5WHvAm8iMAZIgYJ4GcEwKU/vdyjcZH9up6eMq1T5Y8vuNRB8/HJc+pu+jk2W8MkmXPvdI4rF0ugEnTw/8vZk7ocgxhAF510yQTd47EAnXk6mFnx3eIrd+sB2CIuIPmTdYiCAszh1uaC3K9g1f59IEFtYfeK/wIKgi/BUH9yqSV7WhDTLIuXvbs+Fs59juBzNGy7UN5stgRDMA/0T6Rw8ywUuyiT1vc5cqLqtZqA1WcugV0npn7uEPMpRwOyreQWTFvhhfHAqMhnvb/9/4="
