#- id: '1531800747691'
#  alias: Lights on before sunset
#  trigger:
#  - event: sunrise
#    offset: -00:30:00
#    platform: sun
#  condition: []
#  action:
#  - data:
#      entity_id: group.lights_inside
#    service: light.turn_on
#  - data:
#      group_name: Living Room
#      scene_name: Normal
#    service: hue.hue_activate_scene
#  - data:
#      group_name: Master
#      scene_name: Normal
#    service: hue.hue_activate_scene
