- id: '1533318250766'
  alias: Timer - Lights off when Vacation
  trigger:
  - at: 00:00
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - alias: ''
    data:
      entity_id: light.inside_lights
    service: light.turn_off
- id: set_theme_at_startup
  alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: dark_blue
- id: '1553624093506'
  alias: Timer - Front Porch
  trigger:
  - entity_id: light.front_porch
    for:
      seconds: 30
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: 
      entity_id: light.front_porch
    service: light.turn_off
- id: '1553624404892'
  alias: Sunset - Inside Lights
  trigger:
  - event: sunset
    offset: '-1800'
    platform: sun
  condition: []
  action:
  - data:
      entity_id: scene.normal
    service: scene.turn_on
- id: '1553624607733'
  alias: Sunset - Front Yard Lights
  trigger:
  - event: sunset
    offset: '600'
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.front_yard
    service: light.turn_on
- id: '1553624732991'
  alias: Sunrise - Front Yard Lights
  trigger:
  - event: sunrise
    offset: '-600'
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.front_yard
    service: light.turn_off
