############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include includes/customize.yaml
  # Customize entities matching a pattern
  customize_glob:
    "switch.zone_*":
      icon: mdi:water-pump

http:
  base_url: !secret base_url
  api_password: !secret http_password
#  server_host: !secret server_host
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 172.20.0.0/24
    - 192.168.100.0/24
    - 192.168.200.0/24
    - 2001:DB8:ABCD::/48

# Fing Pannel
panel_iframe:
  fing_app: #need to change url in secret.yaml to /login to allow device to log in, then add agent_id at url
    title: Fing Scan
    icon: mdi:image-filter-tilt-shift
    url: !secret fing_url
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump
#  unifi_app:
#    title: UniFi Configuration
#    icon: mdi:adjust
#    url: !secret unifi_url

history:

# Optional, allows Home Assistant developers to focus on popular components.
updater:
  reporting: no
  # include_used_components: true

input_boolean:
  vacation_mode:
    name: Vacation Mode
    initial: off
    icon: mdi:home-circle

frontend:
  themes: !include themes/midnight.yaml
#  themes: !include_dir_merge_named themes/

discovery:
  ignore:
    - plex_mediaserver
    - harmony

sun:
  elevation: 210

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Enable the embedded mqtt service in hassio
mqtt:
  embedded:

# Entry to enable the cloud component
cloud:
  google_actions: !include includes/google_actions.yaml

# Entry to enable configuration panel
config:


############################################################
#
# Components
#
############################################################

#google:
#  client_id: !secret google_calendar_client_id
#  client_secret: !secret google_calendar_client_secret

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
#  discovery: false

remote:
  - platform: harmony
    name: !secret harmony_name
    host: !secret harmony_host

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
#    service: tts.google_say
#    data:
#      message: 'May the Force be with you.'

###########################################################
#
# Includes
#
############################################################

# Single Files

camera: !include includes/cameras.yaml
vera:   !include includes/vera.yaml
switch: !include includes/switch.yaml #includes Rachio config
media_player: !include includes/media_players.yaml
#google_assistant: !include includes/google_assistant.yaml
hue: !include includes/philips_hue.yaml
notify: !include includes/notify.yaml
scene: !include includes/scenes.yaml
device_tracker: !include includes/device_tracker.yaml
zone: !include includes/zones.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
light: !include includes/light_strip.yaml


# Group Merge Directory

group: !include_dir_merge_named group/
sensor: !include_dir_merge_list sensors/
automation: !include_dir_merge_list automation/

# -----
#scene: !include includes/scenes.yaml
#weblink: !include includes/weblink.yaml

# Merge List
#automation: !include_dir_merge_list includes/automation
#sensor: !include_dir_merge_list includes/sensors
#shell_command: !include_dir_merge_named includes/shell_command
#zone: !include_dir_merge_list includes/zone

# Merge Named
#group: !include group/irrigation.yaml
#group: !include group/lights.yaml

#script: !include_dir_merge_named includes/scripts
