############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  # customize: !include includes/customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 172.20.0.0/24
        - 192.168.100.0/24
        - 192.168.200.0/24
        - 2001:DB8:ABCD::/48

http:
  base_url: !secret base_url
  # ssl_certificate: /home/homeassistant/.homeassistant/ssl/certificate.pem
  # ssl_key: /home/homeassistant/.homeassistant/ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3

history:

system_health:

# Optional, allows Home Assistant developers to focus on popular components.
updater:
  reporting: no
  # include_used_components: true

input_boolean:
  vacation_mode:
    name: Vacation Mode
    initial: off

frontend:
 themes: !include_dir_merge_named themes/

discovery:
  ignore:
    - plex_mediaserver
    - harmony

sun:
  elevation: 210

# View all events in a logbook
logbook:

# Enable the embedded mqtt service in hassio
# mqtt:
#   embedded:

# Entry to enable configuration panel
config:

# Enable Lovelace YAML Mode
lovelace:
  mode: yaml

############################################################
# Components
############################################################

# Entry to enable the cloud component
# cloud:
#   google_actions: !include includes/google_actions.yaml

#google:
#  client_id: !secret google_calendar_client_id
#  client_secret: !secret google_calendar_client_secret

# netatmo:
#   api_key: !secret netatmo_api_key
#   secret_key: !secret netatmo_secret_key
#   username: !secret netatmo_username
#   password: !secret netatmo_password
# #  discovery: false

# remote:
#   - platform: harmony
#     name: !secret harmony_name
#     host: !secret harmony_host

weather:
  - platform: darksky
    api_key: !secret darksky_secret

###########################################################
# Configuration for Xmas
############################################################

shell_command:
  stop_now: curl -X GET "http://192.168.200.120/fppxml.php?command=stopNow"
  exec_thanks_2019: curl -X GET "http://192.168.200.120/fppxml.php?command=startPlaylist&playList=Thanksgiving_2019&repeat=checked"
  exec_christ_2019: curl -X GET "http://192.168.200.120/fppxml.php?command=startPlaylist&playList=Christmas_2019&repeat=checked"
  effect_aidan: curl -X GET "http://192.168.200.120/fppxml.php?command=startPlaylist&playList=_aidan"
  effect_blinky: curl -X GET "http://192.168.200.120/fppxml.php?command=startPlaylist&playList=_blinky"
  effect_butterfly: curl -X GET "http://192.168.200.120/fppxml.php?command=startPlaylist&playList=_butterfly"
  effect_garlands: curl -X GET "http://192.168.200.120/fppxml.php?command=startPlaylist&playList=_garlands"
  effect_morph: curl -X GET "http://192.168.200.120/fppxml.php?command=startPlaylist&playList=_morph"


binary_sensor:
  - platform: ping
    host: 192.168.200.120
    name: fpp-prod
    scan_interval: 30
    count: 2

  - platform: ping
    host: 192.168.200.130
    name: fpp-stage
    scan_interval: 30
    count: 2

  - platform: ping
    host: 192.168.201.15
    name: falcon-f48
    scan_interval: 30
    count: 2

sensor:
  - platform: command_line
    name: Current Playlist
    command: curl -sS -X GET 'http://192.168.200.120/fppxml.php?command=getFPPstatus' | awk -F 'CurrentPlaylist' '{print $2}' | tr -d '<>/' | head -n 1
    scan_interval: 5
  - platform: command_line
    name: Current Sequence
    command: curl -sS -X GET 'http://192.168.200.120/fppxml.php?command=getFPPstatus' | awk -F 'CurrentSeqName' '{print $2}' | tr -d '<>/' | head -n 1
    scan_interval: 5

###########################################################
# Includes
############################################################

# Single Files

hue: !include includes/philips_hue.yaml
vera:   !include includes/vera.yaml
# google_assistant: !include includes/google_assistant.yaml
# notify: !include includes/notify.yaml
scene: !include includes/scenes.yaml
# device_tracker: !include includes/device_tracker.yaml
light: !include includes/light_groups.yaml

# Group Merge Directory

group: !include_dir_merge_named group/
# sensor: !include_dir_merge_list sensors/
automation: !include automations.yaml
