############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  # customize: !include includes/customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 172.20.0.0/24
        - 192.168.100.0/24
        - 192.168.200.0/24
        - 2001:DB8:ABCD::/48

http:
  base_url: !secret base_url
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3

history:

system_health:

# Optional, allows Home Assistant developers to focus on popular components.
updater:
  reporting: no
  # include_used_components: true

# input_boolean:
#   vacation_mode:
#     name: Vacation Mode
#     initial: off
#     icon: mdi:beach
  # halloween_mode:
  #   name: Halloween Mode
  #   initial: off
    # icon: /local/icon-halloween-org.png

frontend:
#  themes: !include themes/midnight.yaml
 themes: !include_dir_merge_named themes/

discovery:
  ignore:
    - plex_mediaserver
    - harmony

sun:
  elevation: 210

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables a map showing the location of tracked devices
# map:

# Enable the embedded mqtt service in hassio
# mqtt:
#   embedded:

# Entry to enable configuration panel
config:

# Enable Lovelace YAML Mode
lovelace:
  mode: yaml

############################################################
#
# Components
#
############################################################

# Entry to enable the cloud component
# cloud:
#   google_actions: !include includes/google_actions.yaml

#google:
#  client_id: !secret google_calendar_client_id
#  client_secret: !secret google_calendar_client_secret

# netatmo:
#   api_key: !secret netatmo_api_key
#   secret_key: !secret netatmo_secret_key
#   username: !secret netatmo_username
#   password: !secret netatmo_password
# #  discovery: false

# remote:
#   - platform: harmony
#     name: !secret harmony_name
#     host: !secret harmony_host

# tts:
#   - platform: google
#     cache: true
#     cache_dir: /tmp/tts
#     time_memory: 300
#    service: tts.google_say
#    data:
#      message: 'May the Force be with you.'

###########################################################
#
# Includes
#
############################################################

# Single Files

hue: !include includes/philips_hue.yaml
vera:   !include includes/vera.yaml
# camera: !include includes/cameras.yaml
# switch: !include includes/switch.yaml #includes Rachio config
# google_assistant: !include includes/google_assistant.yaml
# notify: !include includes/notify.yaml
# scene: !include includes/scenes.yaml
# media_player: !include includes/media_players.yaml
# device_tracker: !include includes/device_tracker.yaml
# zone: !include includes/zones.yaml
# input_select: !include includes/input_select.yaml
# input_number: !include includes/input_number.yaml
# light: !include includes/light_strip.yaml
# dialogflow: !include includes/dialogflow.yaml

# Group Merge Directory

# group: !include_dir_merge_named layout/
# sensor: !include_dir_merge_list sensors/
# automation: !include automations.yaml
# automation old: !include_dir_merge_list automation
