############################################################
#
# Lovelace UI Configuration File
#
############################################################

title: Reyes Manor
background: radial-gradient(crimson, darkgrey)
theme: midnight
views: !include_dir_merge_list ui-views/
