############################################################
#
# Home Assistant Sensors: System
#
############################################################

- platform: systemmonitor
  resources:
    - type: disk_use
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use