############################################################
#
# Home Assistant Sensors
#
############################################################

- platform: travisci
  api_key:  !secret travisci_api
  repository: HomeAssistant
  branch:   master
  monitored_conditions:
    - state
    - last_build_state
    - last_build_finished_at
