############################################################
#
# Home Assistant Sensors: Fitbit
#
############################################################

- platform: fitbit
  monitored_resources:
    - "activities/tracker/steps"
