############################################################
#
# Home Assistant Sensors: Harmony Activity
#
############################################################

  #Uptime to help out HASS uptime
- platform: uptime
  unit_of_measurement: minutes

- platform: template
  sensors:
    # Harmony
    living_room_remote:
      value_template: '{{ states.remote.lroomharmony.attributes.current_activity }}'
    # HASS Uptime
    hassuptime:
      friendly_name: "HASS Uptime"
      value_template: >-
        {% set uptime = states.sensor.uptime.state | round %}
        {% set minutes = (uptime % 60) | int %}
        {% set hours = ((uptime / 60) % 24) | int %}
        {% set days = (uptime / 1440) | int %}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 day
          {%- else -%}
            {{ days }} days
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {{ '%02d' % hours }}:{{ '%02d' % minutes }} hrs
