############################################################
#
# Home Assistant Sensors: Harmony Activity
# Active icon color: #F9C536
############################################################

  #Uptime to help out HASS uptime
- platform: uptime
  unit_of_measurement: minutes

- platform: template
  sensors:
    # Harmony
    living_room_remote:
      value_template: '{{ states.remote.lroomharmony.attributes.current_activity }}'
    # HASS Uptime
    hassuptime:
      friendly_name: "HASS Uptime"
      value_template: >-
        {% set uptime = states.sensor.uptime.state | round %}
        {% set minutes = (uptime % 60) | int %}
        {% set hours = ((uptime / 60) % 24) | int %}
        {% set days = (uptime / 1440) | int %}
        {%- if days > 0 -%}
          {%- if days == 1 -%}
            1 day
          {%- else -%}
            {{ days }} days
          {%- endif -%}
          {{ ', ' }}
        {%- endif -%}
        {{ '%02d' % hours }}:{{ '%02d' % minutes }} hrs
    # Sun State Template
    sun_state:
      friendly_name: "Sun State"
      value_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          Day
        {% else %}
          Night
        {% endif %}
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}
    # Adv Presence
    mark_status:
      value_template: '{{ states.input_select.mark_status_dropdown.state }}'
      friendly_name: 'Mark'
#      entity_id: input_select.mark_status_dropdown
    sandra_status:
      value_template: '{{ states.input_select.sandra_status_dropdown.state }}'
      friendly_name: 'Sandra'
#      entity_id: input_select.sandra_status_dropdown
