- title: Xmas
  icon: mdi:pine-tree
  # Unique path for direct access /lovelace/${path}
  path: xmas
  # Each view can have a different theme applied. Theme should be defined in the frontend.
  theme: dark_christmas
  # The cards to show on this view.
  cards: 

    # Scenes
    - type: entities
      title: Holiday Control
      show_header_toggle: False
      entities:
        - name: Holiday Lights
          entity: light.holiday_group
        - name: Falcon Player - Production
          entity: binary_sensor.fpp_prod
          icon: mdi:raspberry-pi
        - name: Falcon Controller F48
          entity: binary_sensor.falcon_f48
          icon: mdi:chip
        - name: Falcon Player - Staging
          entity: binary_sensor.fpp_stage
          icon: mdi:raspberry-pi

    - type: entities
      title: What's Playing?
      show_header_toggle: False
      entities:
        - name: Current Playlist
          entity: sensor.current_playlist
          icon: mdi:playlist-play
        - name: Current Sequence
          entity: sensor.current_sequence
          icon: mdi:play-outline
          

    - type: vertical-stack
      title: Playlists
      cards:

      - type: horizontal-stack
        cards:
        - type: entity-button
          name: Stop All
          icon: mdi:stop-circle
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.stop_now
        - type: entity-button
          name: Thanksgiving
          icon: mdi:alpha-t-box
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.exec_thanks_2019
        - type: entity-button
          name: Christmas
          icon: mdi:pine-tree-box
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.exec_christ_2019
        - type: entity-button
          name: Aidan
          icon: mdi:space-invaders
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.effect_aidan

      - type: horizontal-stack
        cards:
        - type: entity-button
          name: Blinky
          icon: mdi:emoticon-wink
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.effect_blinky
        - type: entity-button
          name: Butterfly
          icon: mdi:looks
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.effect_butterfly
        - type: entity-button
          name: Garlands
          icon: mdi:ornament
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.effect_garlands
        - type: entity-button
          name: Morph
          icon: mdi:snowman
          entity: scene.normal
          tap_action:
            action: call-service
            service: shell_command.effect_morph

