###########################################################
#
# Home Assistant Automation - Action
#
############################################################

############################################################
# Trigger: When the scene.morning is activated
############################################################
- alias: 'Morning'
  trigger:
    platform:       event
    event_type:     call_service
    event_data:
      domain:       scene
      service:      turn_on
      service_data:
        entity_id:  scene.morning

  condition:
    condition: time
    after: '07:00:00'
    before: '11:00:00'

  action:
  # Setting Hue Lamp
  - service:        hue.hue_activate_scene
    data:
      group_name:   "Living Room"
      scene_name:   "Morning"
  - service:        hue.hue_activate_scene
    data:
      group_name:   "Master"
      scene_name:   "Morning"

  - service: tts.google_say
    entity_id: media_player.master_bedroom_speaker
    data:
      message: "Good Morning Mark. You're the best."

  # Notify Slack about action taken
  - service:        notify.slack
    data_template:
      message: |
        :iphone: *IFTTT BASED AUTOMATION: Morning*
        Executing *Morning* Automation:
        Calling `MORNING` scene from Philips Hue.