###########################################################
#
# Home Assistant Automation: Going to Bed
#
############################################################

############################################################
# Trigger: When the scene.bedtime is activated
############################################################
- alias: 'Bedtime'
  trigger:
    platform:       event
    event_type:     call_service
    event_data:
      domain:       scene
      service:      turn_on
      service_data:
        entity_id:  scene.bedtime

  action:
  # Setting Hue Lamp
  - service:        hue.hue_activate_scene
    data:
      group_name:   "Living Room"
      scene_name:   "Bedtime"
  - service:        hue.hue_activate_scene
    data:
      group_name:   "Master"
      scene_name:   "Bedtime"

  # Remote to turn off
  - service:        remote.turn_off
    entity_id:
    - remote.lroomharmony

  # Lights to turn off
  - service:        light.turn_off
    entity_id:
    - light.master_5
    - light.living_room_tree_7
    - light.mail_table_4
    - light.kitchen_6
    - light.play_room_3
    - light.office_11
    - light.mobile_2_14

  # Notify Slack about action taken
  - service:        notify.slack
    data_template:
      message: |
        :robot_face: *SCENE BASED AUTOMATION: Bedtime*
        Executing *Going to bed* Automation:
        Turning `ON` the `OUTSIDE` lights.
        Turning `OFF` the `INSIDE` lights.
        Turning `OFF` the `LIVING ROOM TV`.
        Calling `BEDTIME` scene from Philips Hue.