###########################################################
#
# Home Assistant Automation: Advanced Presence
# contribution to:
# https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/
############################################################

###########################################################
# Detection States
############################################################
- alias: Mark person as just arrived
  trigger:
    - platform: state
      entity_id: group.mark_trackers
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: group.sandra_trackers
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.mark_trackers' %}
            input_select.mark_status_dropdown
          {% else %}
            input_select.sandra_status_dropdown
          {% endif %}
        option: Just Arrived

- alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: group.mark_trackers
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: group.sandra_trackers
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.mark_trackers' %}
            input_select.mark_status_dropdown
          {% else %}
            input_select.sandra_status_dropdown
          {% endif %}
        option: Just Left

###########################################################
# Timed State Transitions
############################################################
- alias: Mark person as home
  trigger:
    - platform: state
      entity_id: input_select.mark_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.sandra_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.mark_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.sandra_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mark_status_dropdown' %}
            input_select.mark_status_dropdown
          {% else %}
            input_select.sandra_status_dropdown
          {% endif %}
        option: Home

- alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.mark_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.sandra_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mark_status_dropdown' %}
            input_select.mark_status_dropdown
          {% else %}
            input_select.sandra_status_dropdown
          {% endif %}
        option: Away

- alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.mark_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.sandra_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mark_status_dropdown' %}
            input_select.mark_status_dropdown
          {% else %}
            input_select.sandra_status_dropdown
          {% endif %}
        option: Extended Away
    - service:      notify.slack
      data_template:
        message: ""
        target: ["#notifications"]
        data:
          attachments:
            - color:  "#304FFE"
              pretext: Presence Notification
              fields:
                - title: Entities
                  value: >
                    {% if trigger.entity_id == 'input_select.mark_status_dropdown' %}
                      Mark Trackers
                    {% else %}
                      Sandra Trackers
                    {% endif %}
                  short: true
                - title: Action
                  value: "`Gone`"
                  short: true
              footer: >
                    {% if trigger.entity_id == 'input_select.mark_status_dropdown' %}
                      ":squirrel: Mark, I miss you... you've been gone so long."
                    {% else %}
                      ":dancer: Sandra, I miss you... you've been gone so long."
                    {% endif %}

###########################################################
# Set Away state if device not present at reboot
############################################################

- alias: Place Mark in away when home assistant starts
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.mark_trackers
        state: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mark_status_dropdown
        option: Away

- alias: Place Sandra in away when home assistant starts
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.sandra_trackers
        state: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sandra_status_dropdown
        option: Away