###########################################################
#
# Home Assistant Automation: Home Status
#
############################################################

###########################################################
# Timed State Transitions
############################################################

- alias: Set Home Status to Home
  trigger:
    - platform: state
      entity_id: group.house_trackers
      from: 'not_home'
      to: 'home'
#      for:
#        minutes: 3
  condition:
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_status_dropdown
        option: Home
    - service:        notify.slack_notify
      data_template:
        message: |
          :house: *SETTING HOME STATUS: Home*

- alias: Set Home Status to Away
  trigger:
    - platform: state
      entity_id: group.house_trackers
      from: 'home'
      to: 'not_home'
#      for:
#        minutes: 3
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_status_dropdown
        option: Away
    - service:        notify.slack_notify
      data_template:
        message: |
          :lock: *SETTING HOME STATUS: Away*

###########################################################
# Set Extended Away state if device not present for 24 hours
############################################################

- alias: Set House as extended away
  trigger:
    - platform: state
      entity_id: input_select.home_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.home_status_dropdown
        option: Extended Away
    - service:        notify.slack_notify
      data_template:
        message: |
          :alarm_clock: *SETTING HOME STATUS: Extended Away*

###########################################################
# Set Away state if device not present at reboot
############################################################

- alias: Place Mark in away when home assistant starts
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.house_trackers
        state: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_status_dropdown
        option: Away