###########################################################
#
# Home Assistant Automation: Light Groups
#
############################################################

############################################################
# Trigger: Monitor TV remote
# Action: Turn *on* TV Light
############################################################
- id: turn_on_tv_light
  alias: 'Turn ON the TV Light'
  trigger:
    platform:     state
    entity_id:    remote.lroomharmony
    from:        "off"
    to:          "on"

  action:
  # Lights to turn on
  - service:      light.turn_on
    entity_id:    light.mobile_1_33

- alias: 'Turn OFF the TV Light'
  trigger:
    platform:     state
    entity_id:    remote.lroomharmony
    from:        "on"
    to:          "off"

  action:
  # Lights to turn of
  - service:      light.turn_off
    entity_id:    light.mobile_1_33



############################################################
# Trigger: Prior to sunset
# Action: Turn *on* INSIDE Lights
############################################################
- id: turn_on_inside_lights
  alias: 'Turn ON the INSIDE Lights'
  trigger:
    platform:     sun
    event:        sunset
    offset:      "-00:30:00"

  action:
  # Setting Hue Lamp
  - service:      hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Normal"
  - service:      hue.hue_activate_scene
    data:
      group_name: "Master"
      scene_name: "Normal"

  # Lights to turn on
  - service:      light.turn_on
    entity_id:    group.lights_inside

  # Notify SparkRoom about action taken
  - service:  notify.spark
    data_template:
      message: |
        ## -30 min's till **SUNSET**.
        Turning `ON` the `INSIDE` lights.

  # Notify Slack about action taken
  - service:      notify.slack
    data_template:
      message: ""
      target: ["#homeautomations"]
      data:
        attachments:
          - color:  "#439FE0"
            pretext: House Automation
            fields:
              - title: Trigger
                value: Sunset -30 min
                short: true
              - title: Action
                value: "`Turn On`"
                short: true
              - title: Entities
                value: |
                  Hue Living Room
                  Hue Master
                  Vera Inside
                short: false
            footer: ":sunny: Sun Based Automations"

############################################################
# Trigger: Prior to SUNSET
# Action: Turn *on* OUTSIDE Lights
############################################################
- id: turn_on_outside_lights
  alias: 'Turn ON the OUTSIDE Lights'
  trigger:
    platform:   sun
    event:      sunset
    offset:     "+00:10:00"

  action:
  # Lights to turn on
  - service:    light.turn_on
    entity_id:  group.lights_outside

  # Notify SparkRoom about action taken
  - service:  notify.spark
    data_template:
      message: |
        ## +10 min's past **SUNSET**.
        Turning `ON` the `OUTSIDE` lights.

  # Notify Slack about action taken
  - service:      notify.slack
    data_template:
      message: ""
      target: ["#homeautomations"]
      data:
        attachments:
          - color:  "#439FE0"
            pretext: House Automation
            fields:
              - title: Trigger
                value: Sunset +10 min
                short: true
              - title: Action
                value: "`Turn On`"
                short: true
              - title: Entities
                value: |
                  Vera Front Lights
                short: false
            footer: ":sunny: Sun Based Automations"

############################################################
# Trigger: Prior to SUNRISE
# Action: Turn *off* OUTSIDE Lights
############################################################
- id: turn_off_outside_lights
  alias: 'Turn OFF the OUTSIDE Lights'
  trigger:
    platform:   sun
    event:      sunrise
    offset:     "-00:15:00"

  action:
  # Lights to turn off
  - service:    light.turn_off
    entity_id:  group.lights_outside

  - service:  notify.spark
    data_template:
      message: |
        ## -15 min's till **SUNRISE**.
        Turning `OFF` the `OUTSIDE` lights.

  # Notify Slack about action taken
  - service:      notify.slack
    data_template:
      message: ""
      target: ["#homeautomations"]
      data:
        attachments:
          - color:  "#439FE0"
            pretext: House Automation
            fields:
              - title: Trigger
                value: Sunrise -15 min
                short: true
              - title: Action
                value: "`Turn Off`"
                short: true
              - title: Entities
                value: |
                  Vera Front Lights
                short: false
            footer: ":sunny: Sun Based Automations"
