###########################################################
#
# Home Assistant Automation: Away Mode Automations
#
############################################################

############################################################
# Audible triggers
############################################################
- alias: Audible detected
  trigger:
    - platform: state
      entity_id: sensor.noise_level
      from: 'Quiet'
  condition:
    condition: state
    entity_id: sensor.home_status
    state: 'Away'
  action:
  # Notify Slack about action taken
  - service:      notify.slack
    data_template:
      message: ""
      target: ["#notifications"]
      data:
        attachments:
          - color:  "#D50000"
            pretext: Security Notification
            thumb_url: "https://github.com/mrreyes512/HomeAssistant/blob/develop/www/icon-volume-high_lg.png?raw=true"
            fields:
              - title: Trigger
                value: Netatmo Sensor
                short: true
              - title: Issue
                value: Noise Herd
                short: true
              - title: Current State
                value: "Noise Level : {{ states.sensor.netatmo_indoor_noise.state }}"
                short: false
            footer: ":loud_sound: I herd Something"
