###########################################################
#
# Home Assistant Automation: Advanced Presence
#
############################################################

############################################################
# Detection States
############################################################
- alias: Mark presence detected
  trigger:
    - platform: state
      entity_id: group.mark_trackers
      from: 'not_home'
      to: 'home'
  action:
  # Notify Slack about action taken
  - service:  notify.slack_notify
    data_template:
      message: ""
      target: ["#notifications"]
      data:
        attachments:
          - title:  Presence Notification
          - footer: >
              {% if is_state('group.mark_trackers', 'home') %} :squirrel: Welcome Home Mark
              {% elif is_state('group.mark_trackers', 'not_home') %} :squirrel: Goodbye Mark
              {% endif %}
          - text: >
              Mark
              {% if is_state('group.mark_trackers', 'home') %} Detected
              {% elif is_state('group.mark_trackers', 'not_home') %} Disappeared
              {% endif %}

- alias: Mark presence gone
  trigger:
    - platform: state
      entity_id: group.mark_trackers
      from: 'home'
      to: 'not_home'
  action:
  # Notify Slack about action taken
  - service:  notify.slack_notify
    data_template:
      message: ""
      target: ["#notifications"]
      data:
        attachments:
          - title:  Presence Notification
          - footer: >
              {% if is_state('group.mark_trackers', 'home') %} :squirrel: Welcome Home Mark
              {% elif is_state('group.mark_trackers', 'not_home') %} :squirrel: Goodbye Mark
              {% endif %}
          - text: >
              Mark
              {% if is_state('group.mark_trackers', 'home') %} Detected
              {% elif is_state('group.mark_trackers', 'not_home') %} Disappeared
              {% endif %}

- alias: Sandra presence detected
  trigger:
    - platform: state
      entity_id: group.sandra_trackers
      from: 'not_home'
      to: 'home'
  action:
  # Notify Slack about action taken
  - service:  notify.slack_notify
    data_template:
      message: ""
      target: ["#notifications"]
      data:
        attachments:
          - title:  Presence Notification
          - footer: >
              {% if is_state('group.sandra_trackers', 'home') %} :dancer: Welcome Home Sandra
              {% elif is_state('group.sandra_trackers', 'not_home') %} :dancer: Goodbye Sandra
              {% endif %}
          - text: >
              Mark
              {% if is_state('group.sandra_trackers', 'home') %} Detected
              {% elif is_state('group.sandra_trackers', 'not_home') %} Disappeared
              {% endif %}

- alias: Sandra presence gone
  trigger:
    - platform: state
      entity_id: group.sandra_trackers
      from: 'home'
      to: 'not_home'
  action:
  # Notify Slack about action taken
  - service:  notify.slack_notify
    data_template:
      message: ""
      target: ["#notifications"]
      data:
        attachments:
          - title:  Presence Notification
          - footer: >
              {% if is_state('group.sandra_trackers', 'home') %} :dancer: Welcome Home Sandra
              {% elif is_state('group.sandra_trackers', 'not_home') %} :dancer: Goodbye Sandra
              {% endif %}
          - text: >
              Mark
              {% if is_state('group.sandra_trackers', 'home') %} Detected
              {% elif is_state('group.sandra_trackers', 'not_home') %} Disappeared
              {% endif %}
