############################################################
#
# Home Assistant Device Tracker
#
############################################################

############################################################
# Unifi home
############################################################

- platform: unifi
  username: !secret unifi_username
  password: !secret unifi_password
  host:     !secret unifi_host
  verify_ssl: false