############################################################
#
# Home Assistant Media Players
#
############################################################

- platform: plex
  scan_interval: 3

#- platform: samsungtv
#  host: !secret samsung_tv_ip

- platform: cast
  host: !secret cast_ip_1

- platform: cast
  host: !secret cast_ip_2

- platform: cast
  host: !secret cast_ip_3

- platform: spotify
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret
#  aliases:
#      abc123def456: 'Living Room'
#      9183abas000: 'Bed Room'

#- platform: pandora